# vim: set ft=yaml:

proxy_upstream: http://127.0.0.1:9090
proxy_domains: a.txt
no_proxy_domains: b.txt
pac_tmpl: proxy.tmpl
proxy_dest: "127.0.0.1:9999"
proxy_default: "127.0.0.1:9001"

# when provide certficate file, server will listen https and enable http2
listen:
  - addr: 0.0.0.0
    port: 9001
    certificates:

# virtual host support
docroot: /srv/www

proxy:
  http1-proxy: false
  http2-proxy: true
  # trust the follow domains as local virtual host
  # when http2 proxy enabled
  localdomains:
    - localhost
    - localdomain
    - 127.0.0.1
    - ratafee.nl
    - 98.142.138.194
